### ISSUE TITLE
linked blogpost is not found (404)

### ISSUE THREAD

**Issue by Simon-Laux** [crabnebula-dev/koi-pond#13]
The url https://crabnebula.dev/blog/building-a-desktop-pet-with-tauri results in 404 when I try to open it.

**Comment by denjell-crabnebula** [comment]
You're right! We're working on it and will keep this issue open until we fix a couple styling issues.

**Comment by denjell-crabnebula** [comment]
Found the mistake and waiting for review and we will be publishing the full article today.

**Comment by denjell-crabnebula** [comment]
Fixed and published
